### ISSUE TITLE
Publish on pypi?

### ISSUE THREAD

**Issue by erikogabrielsson** [anibali/pyisyntax#3]
Hi,

This looks like a great wrapper for libisyntax, and I would like to use it as a input source for [wsidicomizer](https://github.com/imi-bigpicture/wsidicomizer) to enable converting isyntax files to DICOM. Would you consider putting the package on pypi?

**Comment by anibali** [comment]
It is already on PyPI: https://pypi.org/project/pyisyntax/. I will add a mention of this in the README.

Also, stay tuned for the 0.1.2 release incorporating recent changes.

**Comment by anibali** [comment]
v0.1.2 is now available.

**Comment by erikogabrielsson** [comment]
Sorry, must have somehow missed that it was already there. Thanks
